parse_file_path: null
text_corpus_save_path: ~/.local/share/zotero-research-assistant/corpora/text.jsonl
image_corpus_save_path: ~/.local/share/zotero-research-assistant/corpora/image.jsonl

mineru_dir: ~/.local/share/zotero-research-assistant/corpora/
mineru_extra_params:
  source: modelscope

raw_chunk_path: ~/.local/share/zotero-research-assistant/corpora/text.jsonl
chunk_path: ~/.local/share/zotero-research-assistant/corpora/chunks.jsonl
use_title: false
chunk_backend: sentence
tokenizer_or_token_counter: character
chunk_size: 512
chunk_backend_configs:
  sentence:
    chunk_overlap: 50
    min_sentences_per_chunk: 1
    delim: "['.', '!', '?', '；', '。', '！', '？', '\\n']"
