model_name_or_path: openbmb/MiniCPM-Reranker-Light
backend: sentence_transformers
backend_configs:
  sentence_transformers:
    device: cpu
    trust_remote_code: true

gpu_ids: null
top_k: 5
batch_size: 16
query_instruction: ""
